name: clean_arch_bookly_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  go_router: ^8.0.2
  dio: ^5.2.1+1

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  hive: ^2.2.3
  hive_flutter: 
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
  build_runner:

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/test_image.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700,
